version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hafidh2001/cp-antrean-truck:latest
    container_name: cp-antrean-truck
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - app-network

  # Development service
  dev:
    image: node:20-alpine
    container_name: cp-antrean-truck-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge